import {Metadata} from "next";
import {ClerkProvider} from "@clerk/nextjs";
import {Inter} from "next/font/google";
import { dark } from "@clerk/themes";

import "../../globals.css"

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Auth",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider
            appearance={{
                baseTheme: dark,
            }}
        >
            <html lang='en'>
            <body className={`${inter.className} bg-dark-1 flex items-center justify-center h-full`}>{children}</body>
            </html>
        </ClerkProvider>
    );
}